name: Detect Version
description: Detects the version within the source code per the language detected

inputs:
  regex:
    description: The regex to use to match the version
    required: false
    default: '[0-9]*\.[0-9]*\.[0-9]*'

outputs:
  current:
    description: The current version of the project
    value: ${{ steps.determine-current.outputs.version }}

runs:
  using: composite
  steps:
    - name: Check for JavaScript
      if: hashFiles('package.json') != ''
      shell: bash
      run: |
        echo "JavaScript detected."
        detected_version=$(grep -oP '"version": "\K'${{ inputs.regex }} package.json)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Check for .NET
      if: hashFiles('*.csproj') != ''
      shell: bash
      run: |
        echo ".NET detected."
        for file in *.csproj; do
          [ -e "$file" ] || continue
          detected_version=$(grep -oP '<Version>\K'${{ inputs.regex }} "$file")
          echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV
        done

    - name: Check for .NET
      if: hashFiles('Directory.Build.props') != ''
      shell: bash
      run: |
        echo ".NET detected."
        detected_version=$(grep -oP '<Version>\K'${{ inputs.regex }} Directory.Build.props)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Check for Python
      if: hashFiles('setup.py') != ''
      shell: bash
      run: |
        echo "Python detected."
        detected_version=$(grep -oP "version='\K${{ inputs.regex }}" setup.py)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Check for Python
      if: hashFiles('pyproject.toml') != ''
      shell: bash
      run: |
        echo "Python detected."
        detected_version=$(grep -oP 'version = "\K'${{ inputs.regex }} pyproject.toml)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Check for Java
      if: hashFiles('build.gradle') != ''
      shell: bash
      run: |
        echo "Java detected."
        detected_version=$(grep -oP 'version = "\K'${{ inputs.regex }} build.gradle)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Check for Kotlin
      if: hashFiles('build.gradle.kts') != ''
      shell: bash
      run: |
        echo "Kotlin detected."
        detected_version=$(grep -oP 'version = "\K'${{ inputs.regex }} build.gradle.kts)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Find PR label(s) from Commit
      id: find
      if: env.DETECTED_VERSION == ''
      shell: bash
      run: |
        echo "Finding PR associated with commit $GITHUB_SHA..."
        PR_JSON=$(gh pr list --state merged --json number,labels,mergeCommit --jq ".[] | select(.mergeCommit == \"$GITHUB_SHA\")")
        if [ -z "$PR_JSON" ]; then
          echo "No PR found for commit $GITHUB_SHA"
          exit 0
        fi
        echo "PR found: $PR_JSON"

        PR_LABELS=$(jq -r '.labels[].name' <<< "$PR_JSON" | tr '\n' ' ')
        echo "Labels found: $PR_LABELS"

        if [[ $PR_LABELS =~ major ]]; then
          INCREMENT="major"
        elif [[ $PR_LABELS =~ minor ]]; then
          INCREMENT="minor"
        elif [[ $PR_LABELS =~ patch ]]; then
          INCREMENT="patch"
        else
          INCREMENT="minor"
        fi

        echo "Determined label: $INCREMENT"
        echo "increment=$INCREMENT" >> $GITHUB_OUTPUT

    - name: Detect Next Tag
      uses: gitops-ci-cd/.github/actions/check_tag@main
      id: check-tag
      if: env.DETECTED_VERSION == ''
      with:
        increment: ${{ steps.find.outputs.increment }}

    - name: Check for unknown language
      if: env.DETECTED_VERSION == ''
      env:
        detected_version: ${{ steps.check-tag.outputs.next }}
      shell: bash
      run: |
        echo "Unknown language detected."
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Output Detected Version
      id: determine-current
      shell: bash
      run: |
        if [ -n "$DETECTED_VERSION" ]; then
          echo "Detected Version: $DETECTED_VERSION"
        else
          DETECTED_VERSION=0.0.0
          echo "No version detected!"
        fi
        echo "version=$DETECTED_VERSION" >> $GITHUB_OUTPUT
