name: Deploy
description: Deploy a GitHub environment

inputs:
  environment:
    description: Environment to deploy to
    default: production

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      env:
        TARGET_ENV: ${{ inputs.environment }}
      with:
        github-token: ${{ github.token }}
        script: |
          const { TARGET_ENV } = process.env
          console.log(`Deploying to ${TARGET_ENV}...`);
          const response = await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.payload?.pull_request?.head?.ref || context.sha,
            required_contexts: [],
            environment: TARGET_ENV,
            transient_environment: TARGET_ENV === 'preview',
            description: `Deploying to ${TARGET_ENV}...`
          });
          console.log(`  Deployment created with ID: ${response.data.id}`);
