name: Enforce SemVer
description: Enforces SemVer labels on Pull Requests

outputs:
  increment:
    description: The SemVer increment to use
    value: ${{ steps.increment.outputs.label }}

runs:
  using: composite
  steps:
    - name: Check for "patch" Label
      if: contains(github.event.pull_request.labels.*.name, 'patch')
      shell: bash
      run: |
        echo "Found 'patch' label."
        echo "INCREMENT_LABEL=patch" >> $GITHUB_ENV
    - name: Check for "minor" Label
      if: contains(github.event.pull_request.labels.*.name, 'minor')
      shell: bash
      run: |
        echo "Found 'minor' label."
        echo "INCREMENT_LABEL=minor" >> $GITHUB_ENV
    - name: Check for "major" Label
      if: contains(github.event.pull_request.labels.*.name, 'major')
      shell: bash
      run: |
        echo "Found 'major' label."
        echo "INCREMENT_LABEL=major" >> $GITHUB_ENV
    - name: Add default Label
      if: env.INCREMENT_LABEL == ''
      shell: bash
      run: |
        increment_label=minor
        echo "INCREMENT_LABEL=$increment_label" >> $GITHUB_ENV
        echo "No valid label found. Adding '$increment_label'."
        gh pr edit $PR_NUMBER --add-label $increment_label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
    - name: Increment
      shell: bash
      id: increment
      run: |
        echo "label=$INCREMENT_LABEL" >> $GITHUB_OUTPUT
