on:
  push:
    branches:
      - $default-branch

name: Docker Image

permissions:
  packages: write
  attestations: write
  id-token: write
  
jobs:
  docker:
    uses: gitops-ci-cd/.github/.github/workflows/docker_image.yml@main
