on: pull_request

permissions:
  contents: read

name: Integrate code

jobs:
  lint:
    uses: gitops-ci-cd/.github/.github/workflows/lint.yaml@main
  test:
    uses: gitops-ci-cd/.github/.github/workflows/test.yaml@main
