on:
  pull_request:
    types:
      - labeled
      - synchronize

permissions:
  deployments: write

name: Preview Deployment

jobs:
  deployment:
    if: github.event.action == 'labeled' && github.event.label.name == 'preview' || github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'preview')
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: preview
    secrets: inherit
