on:
  push:
    paths-ignore:
      - .devcontainer/**
      - .github/**
      - .vscode/**
      - .gitignore
      - Brewfile
      - README.md
    branches:
      - $default-branch

permissions:
  contents: write

name: Tag & Release Repository

jobs:
  tag:
    uses: gitops-ci-cd/.github/.github/workflows/tag_release.yaml@main
