# https://docs.github.com/en/rest/deployments/statuses?apiVersion=2022-11-28#create-a-deployment-status

name: Update Deployment Status
description: Looks up the latest deployment for a ref and updates its status

inputs:
  ref:
    description: The name of the ref. This can be a branch, tag, or SHA.
    required: true
  state:
    description: The state of the status. When you set a transient deployment to inactive, the deployment will be shown as destroyed in GitHub.
    required: true
  environment:
    description: Name for the target deployment environment, which can be changed when setting a deploy status.
  environment_url:
    description: Sets the URL for accessing your environment.
  log_url:
    description: This URL should contain output to keep the user updated while the task is running or serve as historical information for what happened in the deployment.

runs:
  using: composite
  steps:
    - name: Query Latest Deployment ID
      id: query
      uses: actions/github-script@v7
      with:
        script: |
          console.log(`Querying latest deployment for ref: ${inputs.ref}`);

          const response = await github.repos.listDeployments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: inputs.ref,
          });

          if (!response.data.length) {
            core.setFailed(`No deployments found for ref: ${inputs.ref}`);
            return;
          }

          const id = response.data[0].id;

          console.log(`  Latest deployment ID: ${id}`);

          return id;
        result-encoding: string

    - name: Update Deployment Status
      uses: actions/github-script@v7
      with:
        script: |
          console.log(`Updating deployment status...`);
          console.log("context", context);
          console.log("inputs", inputs);

          await github.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: ${{ steps.query.outputs.result }},
            state: inputs.state,
            environment: inputs.environment,
            environment_url: inputs.environment_url,
            log_url: inputs.log_url,
            description: "Deployment status updated via repository_dispatch",
          });

          console.log(`  Deployment status updated to ${inputs.state}!`);
