# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images

on:
  workflow_call:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

name: Build & Push Container Image

jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitops-ci-cd/.github/actions/build@main
