# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: Tag version to release
        required: true

permissions:
  contents: write

name: Release Repository

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ inputs.version }}
        run: |
          gh release create "v${VERSION}" --title "Version ${VERSION}" --notes "Release version ${VERSION}" --target ${{ github.sha }}
