# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases
# https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow

on:
  workflow_call:
    secrets:
      PAT:
        description: Personal Access Token (PAT) used to authenticate with GitHub
        required: true

permissions:
  contents: write
name: Release Repository
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.PAT }}
          VERSION: ${{ github.ref }}
          SHA: ${{ github.sha }}
        run: |
          gh release create "v${VERSION}" --title "Version ${VERSION}" --notes "Released via GitHub Actions" --verify-tag --target $SHA
