# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

on:
  workflow_call:

permissions:
  contents: read

name: Test

jobs:
  docker_compose_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          target: builder
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: docker compose run --rm install
      - run: docker compose run --rm test
