# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

name: Version Bump

jobs:
  bump:
    name: Bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: gitops-ci-cd/.github/actions/enforce_semver@main
        id: semver
      - uses: gitops-ci-cd/.github/actions/check_version@main
        id: version
        with:
          increment: ${{ steps.semver.outputs.increment }}
      - uses: gitops-ci-cd/.github/actions/update_version@main
        with:
          version: ${{ steps.version.outputs.next }}
